### ISSUE TITLE
Remove "Second Nav"?

### ISSUE THREAD

**Issue by mysterycommand** [potpiedigital/beckybosshart.com#10]
## Don't Do This … Yet

I want to talk about this before we pull the trigger, but maybe we don't even need that secondary nav right now. It used to be a place for social links, but it's turned into a repeat of the main links, plus a menu of in-document links … do we really need it for an MVP? It looks weird right now and it seems like a slightly complicated "nice to have".

Should we remove it for now, and add it back in in a separate PR?

**Comment by Purple906** [comment]
I don't really know that I have input on this. I can do whatever. It does seem a little repetitive. Should we removed the three links on top instead, since the CV will likely be the "resume" in the dropdown? Then we can add in the email and phone? Not sure the best practice.

**Comment by mysterycommand** [comment]
After talking to @Thinkinggood, this seems like an area where we could spend a fair amount of time dicking around for not a lot of value. Let's remove this for now and come back to it once we've got the main site's goals accomplished (hosting Becky's resume and list of links/accomplishments).
