### ISSUE TITLE
Clean up unused markup

### ISSUE THREAD

**Issue by mysterycommand** [potpiedigital/beckybosshart.com#8]
Looks like there's some markup that we don't really need anymore. The `span`s inside the `h6`s. The `div.info`s. Let's have as little markup as possible.

**Comment by Purple906** [comment]
removed the span tags, but the info class on the div's set the margins so everything is indented like in the spec sheet ... are we aligning everything on the left now?

**Comment by mysterycommand** [comment]
Just put `margin: 0 auto; width: 80%;` on the `section` elements.

**Comment by mysterycommand** [comment]
This is fixed in #12 … sorry it's so noisy, I "prettified" your HTML which is why there's so many big chunks of green/red that basically look the same.
