### ISSUE TITLE
Links need values

### ISSUE THREAD

**Issue by mysterycommand** [potpiedigital/beckybosshart.com#9]
We have 3 links at the very top: Download CV, Email, Phone … we need values for these. I'm guessing the CV is going to be a PDF or Word doc. Probably just post that and the email/phone to use in Slack when you get a chance @Thinkinggood.

**Comment by mysterycommand** [comment]
… also I just remembered the MORE PHOTOS links. Gonna need those Flickr album links too.

**Comment by Purple906** [comment]
added CV and Email, currently no phone number listed. Also added flickr but they error out when I try to open. Maybe the flickr albums aren't public?
